### ISSUE TITLE
Various issues in getting Ansible module working

### ISSUE THREAD

**Issue by llawwehttam** [aruba/aoscx-ansible-role#18]
Hi,

I'm running into multiple issues getting this module working and I'm not sure where I'm going wrong.
I have tried to use this module with the following configuration:

Switch Model: JL262A
Firmware: WC.16.11.0002

Switch Configuration:
```
aruba-sw# show web-management

 Web Management - Server Configuration

  HTTP Access    : Disabled
  HTTPS Access   : Enabled
  SSL Port       : 443
  Idle Timeout   : 600 seconds
  Management URL : http://h17007.www1.hpe.com/device_help
  Support URL    : https://www.hpe.com/us/en/networking.html
  User Interface : Improved

aruba-sw# show rest-interface

 REST Interface - Server Configuration

  REST Interface            : Enabled
  REST Operational Status   : Up
  REST Session Idle Timeout : 600 seconds
  HTTP Access               : Disabled
  HTTPS Access              : Enabled
  SSL Port                  : 443
```

Ansible Inventory:
```
---
arubaswitches:
  hosts:
    aruba-sw:
      ansible_host: 192.168.1.1
      ansible_user: manager
      ansible_password: password
      ansible_network_os: aoscx
      ansible_connection: aoscx
      ansible_aoscx_validate_certs: False
      ansible_aoscx_use_proxy: False
      ansible_acx_no_proxy: True
```
Ansible Playbook:
```---
- hosts: aruba-sw
  roles:
    - role: arubanetworks.aoscx_role
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: False
  tasks:
    - name: Create vlan 100
      aoscx_vlan:
        vlan_id: 100
        name: Test
        description: Test
```

I have tried this on two separate machines, the first having the following:
```
ansible [core 2.11.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/admin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
  jinja version = 3.0.2
  libyaml = True
```

This resulted in the following:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/admin/.ansible/tmp/ansible-local-509439bs3sdune/ansible-tmp-1634848834.2162573-509443-203342821847469/AnsiballZ_aoscx_vlan.py", line 100, in <module>
    _ansiballz_main()
  File "/home/admin/.ansible/tmp/ansible-local-509439bs3sdune/ansible-tmp-1634848834.2162573-509443-203342821847469/AnsiballZ_aoscx_vlan.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/admin/.ansible/tmp/ansible-local-509439bs3sdune/ansible-tmp-1634848834.2162573-509443-203342821847469/AnsiballZ_aoscx_vlan.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.aoscx_vlan', init_globals=dict(_module_fqn='ansible.modules.aoscx_vlan', _modlib_path=modlib_path),
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_aoscx_vlan_payload_lmd7lx62/ansible_aoscx_vlan_payload.zip/ansible/modules/aoscx_vlan.py", line 216, in <module>
  File "/tmp/ansible_aoscx_vlan_payload_lmd7lx62/ansible_aoscx_vlan_payload.zip/ansible/modules/aoscx_vlan.py", line 109, in main
  File "/tmp/ansible_aoscx_vlan_payload_lmd7lx62/ansible_aoscx_vlan_payload.zip/ansible/module_utils/aoscx_pyaoscx.py", line 39, in __init__
  File "/tmp/ansible_aoscx_vlan_payload_lmd7lx62/ansible_aoscx_vlan_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: FAIL: Login failed with                status code 400: <HTML><TITLE>400 Bad Request</TITLE><H1>Bad Request</H1>Please login to access the resource.<P></HTML>
fatal: [aruba-sw: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/admin/.ansible/tmp/ansible-local-509439bs3sdune/ansible-tmp-1634848834.2162573-509443-203342821847469/AnsiballZ_aoscx_vlan.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/admin/.ansible/tmp/ansible-local-509439bs3sdune/ansible-tmp-1634848834.2162573-509443-203342821847469/AnsiballZ_aoscx_vlan.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/admin/.ansible/tmp/ansible-local-509439bs3sdune/ansible-tmp-1634848834.2162573-509443-203342821847469/AnsiballZ_aoscx_vlan.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.aoscx_vlan', init_globals=dict(_module_fqn='ansible.modules.aoscx_vlan', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_aoscx_vlan_payload_lmd7lx62/ansible_aoscx_vlan_payload.zip/ansible/modules/aoscx_vlan.py\", line 216, in <module>\n  File \"/tmp/ansible_aoscx_vlan_payload_lmd7lx62/ansible_aoscx_vlan_payload.zip/ansible/modules/aoscx_vlan.py\", line 109, in main\n  File \"/tmp/ansible_aoscx_vlan_payload_lmd7lx62/ansible_aoscx_vlan_payload.zip/ansible/module_utils/aoscx_pyaoscx.py\", line 39, in __init__\n  File \"/tmp/ansible_aoscx_vlan_payload_lmd7lx62/ansible_aoscx_vlan_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: FAIL: Login failed with                status code 400: <HTML><TITLE>400 Bad Request</TITLE><H1>Bad Request</H1>Please login to access the resource.<P></HTML>\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

I then tried this on another machine as follows:
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
```

This resulted in:
```
fatal: [aruba-sw]: FAILED! => {
    "msg": "Could not find imported module support code for aoscx.  Looked for either ComplexList.py or utils.py"
}

```
I have tested the REST interface using Postman and was able to sucessfully authenticate and recieve a cookie.

Can anyone offer any advice?

**Comment by tchiapuziowong** [comment]
Hi @llawwehttam !

I believe you're using the AOS-Switch platform - you'll want to use the AOS-Switch Collection found here on Ansible Galaxy:
https://galaxy.ansible.com/arubanetworks/aos_switch

Here's the repo for this collection:
https://github.com/aruba/aos-switch-ansible-collection

Please reach out on that repo if you have any issues!
